import { addDays, format, startOfDay } from "date-fns";

import type { HolidaySource, PlannerState, Team } from "@/lib/planner/types";
import { makeSlotKey } from "@/lib/planner/calendar";

const today = startOfDay(new Date());

export const seedTeams: Team[] = [
  {
    id: "11111111-1111-4111-8111-111111111111",
    slug: "couverture",
    nameFr: "Equipe Couverture",
    displayOrder: 0,
    accentColor: "oklch(0.6 0.11 212)",
    softColor: "oklch(0.95 0.03 212)",
    isActive: true,
  },
  {
    id: "22222222-2222-4222-8222-222222222222",
    slug: "zinguerie",
    nameFr: "Equipe Zinguerie",
    displayOrder: 1,
    accentColor: "oklch(0.69 0.13 58)",
    softColor: "oklch(0.96 0.04 58)",
    isActive: true,
  },
  {
    id: "33333333-3333-4333-8333-333333333333",
    slug: "maconnerie",
    nameFr: "Equipe Maconnerie",
    displayOrder: 2,
    accentColor: "oklch(0.64 0.12 25)",
    softColor: "oklch(0.95 0.03 25)",
    isActive: true,
  },
];

export const seedHolidaySources: HolidaySource[] = [
  {
    id: "44444444-4444-4444-8444-444444444444",
    code: "FR",
    labelFr: "Jours feries France",
    enabled: true,
  },
];

export const initialPlannerState: PlannerState = {
  teams: seedTeams,
  holidaySources: seedHolidaySources,
  projects: [
    {
      id: "55555555-5555-4555-8555-555555555555",
      title: "Demoussage villa Martin",
      status: "scheduled",
      plannedTeam: seedTeams[0].id,
      estimatedDurationHalfDays: 3,
      scheduledTeam: seedTeams[0].id,
      scheduledStartSlot: makeSlotKey(format(addDays(today, 1), "yyyy-MM-dd"), "AM"),
      scheduledDurationHalfDays: 3,
      sequenceOrder: 0,
      targetDateHint: format(addDays(today, 3), "yyyy-MM-dd"),
      notes: "Nettoyage toiture mecanique et traitement anti-mousse avant controle des tuiles.",
    },
    {
      id: "66666666-6666-4666-8666-666666666666",
      title: "Remplacement tuiles lotissement des Pins",
      status: "scheduled",
      plannedTeam: seedTeams[0].id,
      estimatedDurationHalfDays: 5,
      scheduledTeam: seedTeams[0].id,
      scheduledStartSlot: makeSlotKey(format(addDays(today, 3), "yyyy-MM-dd"), "PM"),
      scheduledDurationHalfDays: 5,
      sequenceOrder: 1,
      targetDateHint: format(addDays(today, 8), "yyyy-MM-dd"),
      notes: "Reprise de 42 tuiles canal et controle complet des rives exposees.",
    },
    {
      id: "77777777-7777-4777-8777-777777777777",
      title: "Solin cheminee maison Bernard",
      status: "scheduled",
      plannedTeam: seedTeams[1].id,
      estimatedDurationHalfDays: 4,
      scheduledTeam: seedTeams[1].id,
      scheduledStartSlot: makeSlotKey(format(addDays(today, 4), "yyyy-MM-dd"), "AM"),
      scheduledDurationHalfDays: 4,
      sequenceOrder: 0,
      targetDateHint: format(addDays(today, 7), "yyyy-MM-dd"),
      notes: "Depose du vieux plomb et pose d'un nouveau solin zinc a tasseaux.",
    },
    {
      id: "88888888-8888-4888-8888-888888888888",
      title: "Zinguerie noue atelier Morel",
      status: "scheduled",
      plannedTeam: seedTeams[1].id,
      estimatedDurationHalfDays: 4,
      scheduledTeam: seedTeams[1].id,
      scheduledStartSlot: makeSlotKey(format(addDays(today, 7), "yyyy-MM-dd"), "AM"),
      scheduledDurationHalfDays: 4,
      sequenceOrder: 1,
      targetDateHint: format(addDays(today, 11), "yyyy-MM-dd"),
      notes: "Remplacement d'une noue centrale avec reprise des raccords lateraux.",
    },
    {
      id: "99999999-9999-4999-8999-999999999999",
      title: "Maconnerie acrotere mairie annexe",
      status: "scheduled",
      plannedTeam: seedTeams[2].id,
      estimatedDurationHalfDays: 6,
      scheduledTeam: seedTeams[2].id,
      scheduledStartSlot: makeSlotKey(format(addDays(today, 5), "yyyy-MM-dd"), "AM"),
      scheduledDurationHalfDays: 6,
      sequenceOrder: 0,
      targetDateHint: format(addDays(today, 10), "yyyy-MM-dd"),
      notes: "Purge des parties fissurees puis reprise de l'acrotere avant retour couverture.",
    },
    {
      id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1",
      title: "Reparation fuite velux Dubois",
      status: "scheduled",
      plannedTeam: seedTeams[0].id,
      estimatedDurationHalfDays: 2,
      scheduledTeam: seedTeams[0].id,
      scheduledStartSlot: makeSlotKey(format(addDays(today, 10), "yyyy-MM-dd"), "AM"),
      scheduledDurationHalfDays: 2,
      sequenceOrder: 2,
      targetDateHint: format(addDays(today, 11), "yyyy-MM-dd"),
      notes: "Intervention SAV apres reprise des solins lateraux et controle d'etancheite.",
    },
    {
      id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa2",
      title: "Recherche infiltration pavillon Leroux",
      status: "draft",
      plannedTeam: seedTeams[0].id,
      estimatedDurationHalfDays: 2,
      targetDateHint: format(addDays(today, 13), "yyyy-MM-dd"),
      notes: "Diagnostic fumigene et ouverture ponctuelle autour de la rive nord.",
    },
    {
      id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa3",
      title: "Zinguerie balcon immeuble Carnot",
      status: "draft",
      plannedTeam: seedTeams[1].id,
      estimatedDurationHalfDays: 4,
      targetDateHint: format(addDays(today, 15), "yyyy-MM-dd"),
      notes: "Habillage en zinc quartz et reprise des bavettes existantes.",
    },
    {
      id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa4",
      title: "Etancheite rive ecole Jules Ferry",
      status: "draft",
      plannedTeam: seedTeams[0].id,
      estimatedDurationHalfDays: 5,
      targetDateHint: format(addDays(today, 18), "yyyy-MM-dd"),
      notes: "Pose d'une bande de rive neuve avec reprise partielle du litonnage.",
    },
    {
      id: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa5",
      title: "Maconnerie cheneau entrepot Lemoine",
      status: "draft",
      plannedTeam: seedTeams[2].id,
      estimatedDurationHalfDays: 4,
      targetDateHint: format(addDays(today, 20), "yyyy-MM-dd"),
      notes: "Reprise des appuis avant intervention zinguerie sur le cheneau encaissé.",
    },
  ],
  dependencies: [
    {
      id: "bbbbbbb1-bbbb-4bbb-8bbb-bbbbbbbbbbb1",
      predecessorProjectId: "99999999-9999-4999-8999-999999999999",
      successorProjectId: "66666666-6666-4666-8666-666666666666",
      lagHalfDays: 0,
    },
    {
      id: "bbbbbbb2-bbbb-4bbb-8bbb-bbbbbbbbbbb2",
      predecessorProjectId: "77777777-7777-4777-8777-777777777777",
      successorProjectId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa1",
      lagHalfDays: 0,
    },
    {
      id: "bbbbbbb3-bbbb-4bbb-8bbb-bbbbbbbbbbb3",
      predecessorProjectId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa5",
      successorProjectId: "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaa3",
      lagHalfDays: 0,
    },
  ],
  closures: [
    {
      id: "ccccccc1-cccc-4ccc-8ccc-ccccccccccc1",
      title: "Fermeture inventaire depot",
      type: "company_closure",
      startDate: format(addDays(today, 18), "yyyy-MM-dd"),
      endDate: format(addDays(today, 18), "yyyy-MM-dd"),
      impact: "blocking",
      details: "Arret total du depot pour inventaire, controle nacelles et livraison materiaux.",
      source: "custom",
      editable: true,
    },
    {
      id: "ccccccc2-cccc-4ccc-8ccc-ccccccccccc2",
      title: "Formation securite harnais",
      type: "custom_time_off",
      startDate: format(addDays(today, 22), "yyyy-MM-dd"),
      endDate: format(addDays(today, 22), "yyyy-MM-dd"),
      impact: "blocking",
      details: "Les trois equipes sont mobilisees en formation securite et travail en hauteur.",
      source: "custom",
      editable: true,
    },
    {
      id: "ccccccc3-cccc-4ccc-8ccc-ccccccccccc3",
      title: "Pluie continue secteur nord",
      type: "weather",
      startDate: format(addDays(today, 10), "yyyy-MM-dd"),
      endDate: format(addDays(today, 10), "yyyy-MM-dd"),
      impact: "advisory",
      details: "Alerte meteo pour les chantiers ouverts. Intervention possible mais cadence reduite a anticiper.",
      source: "custom",
      editable: true,
    },
  ],
  history: {
    canUndo: false,
    canRedo: false,
  },
};
